[package]
name = "fat32"
version = "0.2.0"
edition = "2021"

[dependencies]
spin = "0.9.2"
lru = "0.10.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
riscv = "0.10.1"
time_tracer = { path = "../time_tracer" }
